### PR TITLE
Update to 2.4

### PR DESCRIPTION
**Pull request by judemille**

### CODE REVIEW

**Comment by LorbusChris** [comment]
Thank you for your contribution!

The version is 2.4, not 2.4.2, correct?

Maybe @kaechele has some suggestions on what else to include here from https://github.com/LorbusChris/rspamd-rpm/pull/15

**Comment by judemille** [comment]
The version in https://rspamd.com/rpm-stable/centos-8/x86_64/ is 2.4.2.

**Comment by kaechele** [comment]
It's actually 2.4-2 (dash, not dot).
So Version 2.4 and Release 2.
You will need the replxx patch, otherwise it won't build on F32 and newer.

**Comment by judemille** [comment]
Ah, I missed that. I'm not familiar with the replxx patch, care to send it?

**Comment by kaechele** [comment]
Here's the patch: https://github.com/LorbusChris/rspamd-rpm/pull/15/files#diff-a3809a42b00ce1bcd001bc81654ec292

Check out https://github.com/LorbusChris/rspamd-rpm/pull/15 for other changes that I made that haven't been merged yet. I closed that pull request because I wanted to re-do it with 2.4 but haven't gotten around to it yet.

**Comment by LorbusChris** [comment]
:+1: 
It does seem the replxx patch has merged upstream in https://github.com/AmokHuginnsson/replxx/pull/65

If anybody could PR that update to https://github.com/rspamd/rspamd/tree/master/contrib/replxx too, that'd be awesome! Patching it downstream in the RPM is fine in the meantime.

**Pull request merged**
